name: build

on:
  push:
    branches:
      - develop_st/2.13.x
      - release_st/*
      - master_st

env:
  DOCKERHUB_ORGANIZATION: scanterra
  DOCKERHUB_REPO_NAME: geoserver-docker

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare Docker Image Tag
        id: prep
        run: |
          if [[ ${{ github.ref }} == refs/heads/dev ]]; then
            TAG=$(git rev-parse --short=8 ${{ github.sha }})
          elif [[ ${{ github.ref }} == refs/heads/release/* ]]; then
            TAG=$(echo ${{ github.ref }} | cut -d '/' -f 4)
          elif [[ ${{ github.ref }} == refs/heads/main ]]; then
            TAG=${{ 'latest' }}
          fi
          echo ::set-output name=image_tag::${TAG}
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: docker build -t $DOCKERHUB_REPO_NAME .
      - name: Tags
        run: docker tag $DOCKERHUB_REPO_NAME $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:${{ steps.prep.outputs.image_tag }}
      - name: Push
        run: docker push $DOCKERHUB_ORGANIZATION/$DOCKERHUB_REPO_NAME:${{ steps.prep.outputs.image_tag }}
